# Generated by Django 4.0.4 on 2022-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contatomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizaçao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Caixa'), ('lni-star', 'Estrela')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AlterField(
            model_name='contatomodel',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Mensagem'),
        ),
    ]
