# Generated by Django 4.0.4 on 2022-05-05 13:08

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produtosmodel_alter_contatomodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosmodel',
            name='icone',
        ),
        migrations.AddField(
            model_name='produtosmodel',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, upload_to=core.models.get_file_path, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
